//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CadastrBDEntities : DbContext
    {
        public CadastrBDEntities()
            : base("name=CadastrBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadastre> Cadastre { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Removal_Request> Removal_Request { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
