//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastrProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Removal_Request
    {
        public int Id { get; set; }
        public int IDCadastre { get; set; }
        public int IDOwner { get; set; }
        public int IDStatus { get; set; }
        public string Cause { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Status Status { get; set; }
    }
}
